// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: awesome.proto
package socket.protobuf;
public final class Awesome {
  private Awesome() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AwesomeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AwesomeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    java.lang.String getAwesomeField();
    /**
     * <pre>
     * becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    com.google.protobuf.ByteString
        getAwesomeFieldBytes();
  }
  /**
   * Protobuf type {@code AwesomeMessage}
   */
  public  static final class AwesomeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AwesomeMessage)
      AwesomeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AwesomeMessage.newBuilder() to construct.
    private AwesomeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AwesomeMessage() {
      awesomeField_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AwesomeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              awesomeField_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Awesome.internal_static_AwesomeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Awesome.internal_static_AwesomeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Awesome.AwesomeMessage.class, Awesome.AwesomeMessage.Builder.class);
    }

    public static final int AWESOME_FIELD_FIELD_NUMBER = 1;
    private volatile java.lang.Object awesomeField_;
    /**
     * <pre>
     * becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    public java.lang.String getAwesomeField() {
      java.lang.Object ref = awesomeField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        awesomeField_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
     * </pre>
     *
     * <code>string awesome_field = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAwesomeFieldBytes() {
      java.lang.Object ref = awesomeField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        awesomeField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAwesomeFieldBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, awesomeField_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAwesomeFieldBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, awesomeField_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Awesome.AwesomeMessage)) {
        return super.equals(obj);
      }
      Awesome.AwesomeMessage other = (Awesome.AwesomeMessage) obj;

      boolean result = true;
      result = result && getAwesomeField()
          .equals(other.getAwesomeField());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AWESOME_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getAwesomeField().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Awesome.AwesomeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Awesome.AwesomeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Awesome.AwesomeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Awesome.AwesomeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Awesome.AwesomeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Awesome.AwesomeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Awesome.AwesomeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Awesome.AwesomeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Awesome.AwesomeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Awesome.AwesomeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Awesome.AwesomeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Awesome.AwesomeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Awesome.AwesomeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AwesomeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AwesomeMessage)
        Awesome.AwesomeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Awesome.internal_static_AwesomeMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Awesome.internal_static_AwesomeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Awesome.AwesomeMessage.class, Awesome.AwesomeMessage.Builder.class);
      }

      // Construct using Awesome.AwesomeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        awesomeField_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Awesome.internal_static_AwesomeMessage_descriptor;
      }

      @java.lang.Override
      public Awesome.AwesomeMessage getDefaultInstanceForType() {
        return Awesome.AwesomeMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Awesome.AwesomeMessage build() {
        Awesome.AwesomeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Awesome.AwesomeMessage buildPartial() {
        Awesome.AwesomeMessage result = new Awesome.AwesomeMessage(this);
        result.awesomeField_ = awesomeField_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Awesome.AwesomeMessage) {
          return mergeFrom((Awesome.AwesomeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Awesome.AwesomeMessage other) {
        if (other == Awesome.AwesomeMessage.getDefaultInstance()) return this;
        if (!other.getAwesomeField().isEmpty()) {
          awesomeField_ = other.awesomeField_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Awesome.AwesomeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Awesome.AwesomeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object awesomeField_ = "";
      /**
       * <pre>
       * becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public java.lang.String getAwesomeField() {
        java.lang.Object ref = awesomeField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          awesomeField_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAwesomeFieldBytes() {
        java.lang.Object ref = awesomeField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          awesomeField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public Builder setAwesomeField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        awesomeField_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public Builder clearAwesomeField() {
        
        awesomeField_ = getDefaultInstance().getAwesomeField();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string awesome_field = 1;</code>
       */
      public Builder setAwesomeFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        awesomeField_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AwesomeMessage)
    }

    // @@protoc_insertion_point(class_scope:AwesomeMessage)
    private static final Awesome.AwesomeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Awesome.AwesomeMessage();
    }

    public static Awesome.AwesomeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AwesomeMessage>
        PARSER = new com.google.protobuf.AbstractParser<AwesomeMessage>() {
      @java.lang.Override
      public AwesomeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AwesomeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AwesomeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AwesomeMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Awesome.AwesomeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AwesomeMessage22OrBuilder extends
      // @@protoc_insertion_point(interface_extends:AwesomeMessage22)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *  becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
     * </pre>
     *
     * <code>string test = 2;</code>
     */
    java.lang.String getTest();
    /**
     * <pre>
     *  becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
     * </pre>
     *
     * <code>string test = 2;</code>
     */
    com.google.protobuf.ByteString
        getTestBytes();
  }
  /**
   * Protobuf type {@code AwesomeMessage22}
   */
  public  static final class AwesomeMessage22 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AwesomeMessage22)
      AwesomeMessage22OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AwesomeMessage22.newBuilder() to construct.
    private AwesomeMessage22(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AwesomeMessage22() {
      id_ = 0L;
      test_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AwesomeMessage22(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              test_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Awesome.internal_static_AwesomeMessage22_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Awesome.internal_static_AwesomeMessage22_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Awesome.AwesomeMessage22.class, Awesome.AwesomeMessage22.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TEST_FIELD_NUMBER = 2;
    private volatile java.lang.Object test_;
    /**
     * <pre>
     *  becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
     * </pre>
     *
     * <code>string test = 2;</code>
     */
    public java.lang.String getTest() {
      java.lang.Object ref = test_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        test_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
     * </pre>
     *
     * <code>string test = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTestBytes() {
      java.lang.Object ref = test_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getTestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, test_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getTestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, test_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Awesome.AwesomeMessage22)) {
        return super.equals(obj);
      }
      Awesome.AwesomeMessage22 other = (Awesome.AwesomeMessage22) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getTest()
          .equals(other.getTest());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TEST_FIELD_NUMBER;
      hash = (53 * hash) + getTest().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Awesome.AwesomeMessage22 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Awesome.AwesomeMessage22 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Awesome.AwesomeMessage22 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Awesome.AwesomeMessage22 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Awesome.AwesomeMessage22 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Awesome.AwesomeMessage22 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Awesome.AwesomeMessage22 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Awesome.AwesomeMessage22 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Awesome.AwesomeMessage22 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Awesome.AwesomeMessage22 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Awesome.AwesomeMessage22 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Awesome.AwesomeMessage22 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Awesome.AwesomeMessage22 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AwesomeMessage22}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AwesomeMessage22)
        Awesome.AwesomeMessage22OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Awesome.internal_static_AwesomeMessage22_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Awesome.internal_static_AwesomeMessage22_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Awesome.AwesomeMessage22.class, Awesome.AwesomeMessage22.Builder.class);
      }

      // Construct using Awesome.AwesomeMessage22.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        test_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Awesome.internal_static_AwesomeMessage22_descriptor;
      }

      @java.lang.Override
      public Awesome.AwesomeMessage22 getDefaultInstanceForType() {
        return Awesome.AwesomeMessage22.getDefaultInstance();
      }

      @java.lang.Override
      public Awesome.AwesomeMessage22 build() {
        Awesome.AwesomeMessage22 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Awesome.AwesomeMessage22 buildPartial() {
        Awesome.AwesomeMessage22 result = new Awesome.AwesomeMessage22(this);
        result.id_ = id_;
        result.test_ = test_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Awesome.AwesomeMessage22) {
          return mergeFrom((Awesome.AwesomeMessage22)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Awesome.AwesomeMessage22 other) {
        if (other == Awesome.AwesomeMessage22.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getTest().isEmpty()) {
          test_ = other.test_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Awesome.AwesomeMessage22 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Awesome.AwesomeMessage22) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object test_ = "";
      /**
       * <pre>
       *  becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string test = 2;</code>
       */
      public java.lang.String getTest() {
        java.lang.Object ref = test_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          test_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string test = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTestBytes() {
        java.lang.Object ref = test_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string test = 2;</code>
       */
      public Builder setTest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        test_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string test = 2;</code>
       */
      public Builder clearTest() {
        
        test_ = getDefaultInstance().getTest();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  becomes awesomeField ,特别要注意， 这里下划线后面在初始化的时候， 修改为大写，这里是个大坑. 只有string 类型才这样。
       * </pre>
       *
       * <code>string test = 2;</code>
       */
      public Builder setTestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        test_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AwesomeMessage22)
    }

    // @@protoc_insertion_point(class_scope:AwesomeMessage22)
    private static final Awesome.AwesomeMessage22 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Awesome.AwesomeMessage22();
    }

    public static Awesome.AwesomeMessage22 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AwesomeMessage22>
        PARSER = new com.google.protobuf.AbstractParser<AwesomeMessage22>() {
      @java.lang.Override
      public AwesomeMessage22 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AwesomeMessage22(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AwesomeMessage22> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AwesomeMessage22> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Awesome.AwesomeMessage22 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AwesomeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AwesomeMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AwesomeMessage22_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AwesomeMessage22_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rawesome.proto\"\'\n\016AwesomeMessage\022\025\n\rawe" +
      "some_field\030\001 \001(\t\",\n\020AwesomeMessage22\022\n\n\002" +
      "id\030\001 \001(\003\022\014\n\004test\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AwesomeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AwesomeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AwesomeMessage_descriptor,
        new java.lang.String[] { "AwesomeField", });
    internal_static_AwesomeMessage22_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AwesomeMessage22_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AwesomeMessage22_descriptor,
        new java.lang.String[] { "Id", "Test", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
